apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-data
spec:
  storageClassName: nfs-server
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---      
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  type: LoadBalancer
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        lifecycle:
          postStart:
            exec:
              command: 
                - /bin/sh
                - -c
                - |
                    echo "<h1>Hello, I'm using nfs shared volume</h1>" > /usr/share/nginx/html/index.html
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: www-data