---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-console
  name: kube-console-service
  namespace: kube-console
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: kube-console
  type: ClusterIP