apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: graylog-logging
data:
  elasticsearch.yml: |
    cluster.name: elastic-cluster
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch
    discovery.zen.minimum_master_nodes: 1