apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog-logging
spec:
  selector:
    app: graylog
  ports:
  - name: web
    port: 9000
    targetPort: 9000
  - name: tcp
    port: 12201
    targetPort: 12201