apiVersion: v1
kind: Service
metadata:
  labels:
    app: crowd-server
  name: crowd-server
  namespace: atlassian-crowd
spec:
  ports:
  - name: http
    port: 8095
    protocol: TCP
    targetPort: http
  selector:
    app: crowd-server