apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowd-data
  namespace: atlassian-crowd
spec:
# storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi