apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: crowd-server
  name: crowd-server
  namespace: atlassian-crowd
spec:
  serviceName: crowd-server
  replicas: 1
  selector:
    matchLabels:
      app: crowd-server
  template:
    metadata:
      labels:
        app: crowd-server
    spec:
      initContainers:
      - name: "init-chown-data"
        image: busybox:latest
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: ["chown -R  65534:65534 /var/atlassian/application-data/crowd; chmod -R 777 /var/atlassian/application-data/crowd"]
        volumeMounts:
        - name: crowd-data
          mountPath: /var/atlassian/application-data/crowd
          subPath: ""
      containers:
      - env:
        - name: JVM_MINIMUM_MEMORY
          value: 1024m
        - name: JVM_MAXIMUM_MEMORY
          value: 2048m
        image: dchevell/crowd:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 3
        name: confluence
        ports:
        - containerPort: 8095
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 3
        resources:
          requests:
            memory: 1Gi
        volumeMounts:
        - mountPath: /var/atlassian/application-data/crowd
          name: crowd-data
      volumes:
        - name: crowd-data
          persistentVolumeClaim:
            claimName: crowd-data
