apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: graylog-logging

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: graylog-logging
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: graylog-logging

---
apiVersion:  apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: graylog-logging
  labels:
    app: fluentd-logging
spec:
  selector:
    matchLabels:
      app: fluentd-logging 
  template:
    metadata:
      labels:
        app: fluentd-logging
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.7-debian-graylog-1
        imagePullPolicy: IfNotPresent
        env:
          - name:  FLUENT_GRAYLOG_HOST
            value: "graylog"
          - name:  FLUENT_GRAYLOG_PORT
            value: "12201"
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers