apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira-software
  name: jira-software-service
  namespace: atlassian-jira-software
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: jira-software