apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: prometheus
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: prometheus
  labels: &Labels
    k8s-app: node-exporter
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: node-exporter
spec:
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels: *Labels
    spec:
      serviceAccountName: node-exporter
      containers:
        - name: node-exporter
          image: srinisbook/node-exporter:v1.0
          imagePullPolicy: Always
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
          resources: {}
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys