apiVersion: v1
kind: Service
metadata:
  name: nginx-redirect
  labels:
    app: nginx-redirect
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 80
  type: ClusterIP
  selector:
    app: nginx-redirect