apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-redirect
  labels:
    app: nginx-redirect
spec:
  selector:
    matchLabels:
      app: nginx-redirect
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-redirect
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-rewrite-conf
      containers:
        - image: nginx:1.7.9
          name: nginx-redirect
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: nginx-http
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
