kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  labels:
    app: nginx-redirect
  name: nginx-redirect
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: nginx-redirect
          servicePort: 80
        path: /
  tls:
  - hosts:
    - example.com
    secretName: example-com-tls-cert
