apiVersion: v1
data:
  ELASTICSEARCH_USERNAME: ZWxhc3RpYw==
  #ELASTICSEARCH_PASSWORD: "<base64 encoded password>"
kind: Secret
metadata:
  name: kibana-creds
  namespace: elastic-logging
type: Opaque
