apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: artifactory
  name: artifactory
  namespace: jfrog-artifactory
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: artifactory
  namespace: jfrog-artifactory
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: artifactory
  namespace: jfrog-artifactory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: artifactory
subjects:
- kind: ServiceAccount
  name: artifactory