apiVersion: v1
data:
  master-key: ZjQ3ZWYxNzBhMjVjN2YzNzRkNDlhYmVjZmFmMGE5YTA5N2FiYzY1NGVjZGFhZmE5MTM4N2I1YzU2MjFjYzUxMwo=
kind: Secret
metadata:
  name: master-key-secret
  namespace: jfrog-artifactory
type: Opaque