apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: jfrog-artifactory
spec:
  ports:
  - name: artifactory
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: artifactory
  sessionAffinity: None
  type: LoadBalancer
