apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira-service-desk
  name: jira-service-desk-service
  namespace: atlassian-jira-service-desk
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: jira-service-desk