apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jira-service-desk
  name: jira-service-desk-data
  namespace: atlassian-jira-service-desk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi