apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-data
  namespace: atlassian-confluence
spec:
# storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi