kind: Service
apiVersion: v1
metadata:
  name: bitbucket-server
  labels:
    app: bitbucket
  namespace: atlassian-bitbucket
spec:
  selector:
    app: bitbucket
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 7990
  - name: git
    protocol: TCP
    port: 7999
    targetPort: 7999