apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-workdir
  namespace: atlassian-bitbucket
spec:
# storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi